# Generated by Django 5.2.1 on 2025-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=64)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barangs',
            },
        ),
    ]
