# Generated by Django 5.2.1 on 2025-07-08 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pinjam', models.DateTimeField(default=django.utils.timezone.now)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjam.barang')),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinjam',
                'verbose_name_plural': 'Pinjams',
            },
        ),
    ]
