# Generated by Django 5.2.1 on 2025-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam', '0002_pinjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=16),
        ),
    ]
